-- Egece Transfer - Supabase Veritabanı Kurulum Kodu
-- Bu kodları Supabase panelinizdeki "SQL Editor" kısmına yapıştırıp "Run" butonuna basarak çalıştırabilirsiniz.

-- 1. Rezervasyonlar tablosunu oluşturma
CREATE TABLE IF NOT EXISTS rezervasyonlar (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isim TEXT NOT NULL,
    telefon TEXT NOT NULL,
    nereden TEXT NOT NULL,
    nereye TEXT NOT NULL,
    tarih_saat TIMESTAMPTZ NOT NULL,
    odeme_yontemi TEXT NOT NULL,
    durum TEXT DEFAULT 'Beklemede' NOT NULL,
    olusturma_tarihi TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- 2. Tabloyu dışarıya açma ve RLS (Satır Bazlı Güvenlik) Ayarları
-- Not: Supabase'de anon anahtarıyla doğrudan veri ekleyip çekebilmek için 
-- RLS politikalarını düzenlemeniz gerekir. 
-- Kolaylık sağlaması amacıyla aşağıda herkese ekleme (Insert), okuma (Select) ve güncelleme (Update) izni veren politikalar tanımlanmıştır.

ALTER TABLE rezervasyonlar ENABLE ROW LEVEL SECURITY;

-- Herkesin (müşterilerin) rezervasyon eklemesine izin ver
CREATE POLICY "Müşteriler rezervasyon ekleyebilir" 
ON rezervasyonlar 
FOR INSERT 
TO public 
WITH CHECK (true);

-- Admin panelinin rezervasyonları okumasına izin ver
CREATE POLICY "Rezervasyonları okuma izni" 
ON rezervasyonlar 
FOR SELECT 
TO public 
USING (true);

-- Admin panelinin rezervasyon durumunu güncellemesine izin ver
CREATE POLICY "Rezervasyonları güncelleme izni" 
ON rezervasyonlar 
FOR UPDATE 
TO public 
USING (true)
WITH CHECK (true);
